### ISSUE TITLE
vim.opt.nofoldenable = true

### ISSUE THREAD

**Issue by haunt98** [chivalryq/dotfiles#1]
After searching with github code search, I found that you have same problem with me

Can not do this:

```lua
vim.opt.nofoldenable = true
```

But you can do this:

```lua
vim.opt.foldenable = false
```

Hope it helps!

**Comment by chivalryq** [comment]
Thanks! It's a method from vimscript. In VimScript we can write:
```vim
set nofoo
```

I guess I migrate from there so... Anyway thank you for reminding!

**Comment by haunt98** [comment]
Yeah, I'm just confuse when migrate my init.vim to init.lua (from vimscript to lua) too :D

**Comment by chivalryq** [comment]
I have a article about migration. But it's in Chinese. It may help so I post it here: https://chivalryq.github.io/docs/Neovim/migrate_to_lua

However, some of the api may be outdated for latest neovim.
